"""
    De Lijn Kern Open Data Services (v1)

    Dit document beschrijft de kern operaties van de Open Data API (v1)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import unittest

import delijn_api_kern
from delijn_api_kern.api.routeplan_api import RouteplanApi  # noqa: E501


class TestRouteplanApi(unittest.TestCase):
    """RouteplanApi unit test stubs"""

    def setUp(self):
        self.api = RouteplanApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_geef_routeplan(self):
        """Test case for geef_routeplan

        geef een initëel, vroeger, later of laatste routeplan   # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
