"""
    De Lijn Kern Open Data Services (v1)

    Dit document beschrijft de kern operaties van de Open Data API (v1)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import delijn_api_kern
from delijn_api_kern.model.district import District
from delijn_api_kern.model.link import Link
globals()['District'] = District
globals()['Link'] = Link
from delijn_api_kern.model.districten import Districten


class TestDistricten(unittest.TestCase):
    """Districten unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDistricten(self):
        """Test Districten"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Districten()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
