"""
    De Lijn Kern Open Data Services (v1)

    Dit document beschrijft de kern operaties van de Open Data API (v1)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import delijn_api_kern
from delijn_api_kern.model.lijn_lijnrichtingen import LijnLijnrichtingen
from delijn_api_kern.model.link import Link
globals()['LijnLijnrichtingen'] = LijnLijnrichtingen
globals()['Link'] = Link
from delijn_api_kern.model.lijn_lijnrichtingen_lijst import LijnLijnrichtingenLijst


class TestLijnLijnrichtingenLijst(unittest.TestCase):
    """LijnLijnrichtingenLijst unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLijnLijnrichtingenLijst(self):
        """Test LijnLijnrichtingenLijst"""
        # FIXME: construct object with mandatory attributes with example values
        # model = LijnLijnrichtingenLijst()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
