"""
    De Lijn Kern Open Data Services (v1)

    Dit document beschrijft de kern operaties van de Open Data API (v1)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import delijn_api_kern
from delijn_api_kern.model.duur import Duur
from delijn_api_kern.model.geo_coordinaat import GeoCoordinaat
from delijn_api_kern.model.punt import Punt
from delijn_api_kern.model.reisweg_stap import ReiswegStap
from delijn_api_kern.model.wandel_reisweg_stap_all_of import WandelReiswegStapAllOf
globals()['Duur'] = Duur
globals()['GeoCoordinaat'] = GeoCoordinaat
globals()['Punt'] = Punt
globals()['ReiswegStap'] = ReiswegStap
globals()['WandelReiswegStapAllOf'] = WandelReiswegStapAllOf
from delijn_api_kern.model.wandel_reisweg_stap import WandelReiswegStap


class TestWandelReiswegStap(unittest.TestCase):
    """WandelReiswegStap unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testWandelReiswegStap(self):
        """Test WandelReiswegStap"""
        # FIXME: construct object with mandatory attributes with example values
        # model = WandelReiswegStap()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
