"""
    De Lijn Kern Open Data Services (v1)

    Dit document beschrijft de kern operaties van de Open Data API (v1)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import unittest

import delijn_api_kern
from delijn_api_kern.api.lijnkleuren_api import LijnkleurenApi  # noqa: E501


class TestLijnkleurenApi(unittest.TestCase):
    """LijnkleurenApi unit test stubs"""

    def setUp(self):
        self.api = LijnkleurenApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_geef_lijnkleurcode(self):
        """Test case for geef_lijnkleurcode

        geef een lijnkleur op basis van de opgegeven code  # noqa: E501
        """
        pass

    def test_geef_lijnkleuren(self):
        """Test case for geef_lijnkleuren

        geef alle lijnkleuren  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
