"""
    De Lijn Kern Open Data Services (v1)

    Dit document beschrijft de kern operaties van de Open Data API (v1)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import delijn_api_kern
from delijn_api_kern.model.halte import Halte
from delijn_api_kern.model.link import Link
globals()['Halte'] = Halte
globals()['Link'] = Link
from delijn_api_kern.model.haltes import Haltes


class TestHaltes(unittest.TestCase):
    """Haltes unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testHaltes(self):
        """Test Haltes"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Haltes()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
