"""
    De Lijn Kern Open Data Services (v1)

    Dit document beschrijft de kern operaties van de Open Data API (v1)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import delijn_api_kern
from delijn_api_kern.model.link import Link
from delijn_api_kern.model.nota import Nota
from delijn_api_kern.model.rit import Rit
globals()['Link'] = Link
globals()['Nota'] = Nota
globals()['Rit'] = Rit
from delijn_api_kern.model.ritten import Ritten


class TestRitten(unittest.TestCase):
    """Ritten unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRitten(self):
        """Test Ritten"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Ritten()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
