"""
    De Lijn Kern Open Data Services (v1)

    Dit document beschrijft de kern operaties van de Open Data API (v1)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import delijn_api_kern
from delijn_api_kern.model.link import Link
from delijn_api_kern.model.reisweg import Reisweg
globals()['Link'] = Link
globals()['Reisweg'] = Reisweg
from delijn_api_kern.model.routeplan import Routeplan


class TestRouteplan(unittest.TestCase):
    """Routeplan unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRouteplan(self):
        """Test Routeplan"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Routeplan()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
