"""
    De Lijn Kern Open Data Services (v1)

    Dit document beschrijft de kern operaties van de Open Data API (v1)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import delijn_api_kern
from delijn_api_kern.model.link import Link
from delijn_api_kern.model.omleiding import Omleiding
globals()['Link'] = Link
globals()['Omleiding'] = Omleiding
from delijn_api_kern.model.omleidingen import Omleidingen


class TestOmleidingen(unittest.TestCase):
    """Omleidingen unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOmleidingen(self):
        """Test Omleidingen"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Omleidingen()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
