"""
    De Lijn Kern Open Data Services (v1)

    Dit document beschrijft de kern operaties van de Open Data API (v1)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import delijn_api_kern
from delijn_api_kern.model.halte import Halte
from delijn_api_kern.model.lijnrichting import Lijnrichting
from delijn_api_kern.model.link import Link
from delijn_api_kern.model.periode import Periode
globals()['Halte'] = Halte
globals()['Lijnrichting'] = Lijnrichting
globals()['Link'] = Link
globals()['Periode'] = Periode
from delijn_api_kern.model.omleiding import Omleiding


class TestOmleiding(unittest.TestCase):
    """Omleiding unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOmleiding(self):
        """Test Omleiding"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Omleiding()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
