"""
    De Lijn Kern Open Data Services (v1)

    Dit document beschrijft de kern operaties van de Open Data API (v1)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import delijn_api_kern
from delijn_api_kern.model.geo_coordinaat import GeoCoordinaat
globals()['GeoCoordinaat'] = GeoCoordinaat
from delijn_api_kern.model.wandel_reisweg_stap_all_of import WandelReiswegStapAllOf


class TestWandelReiswegStapAllOf(unittest.TestCase):
    """WandelReiswegStapAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testWandelReiswegStapAllOf(self):
        """Test WandelReiswegStapAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = WandelReiswegStapAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
