"""
    De Lijn Kern Open Data Services (v1)

    Dit document beschrijft de kern operaties van de Open Data API (v1)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import unittest

import delijn_api_kern
from delijn_api_kern.api.districten_api import DistrictenApi  # noqa: E501


class TestDistrictenApi(unittest.TestCase):
    """DistrictenApi unit test stubs"""

    def setUp(self):
        self.api = DistrictenApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_geef_district(self):
        """Test case for geef_district

        geef district  # noqa: E501
        """
        pass

    def test_geef_districten(self):
        """Test case for geef_districten

        geef alle districten  # noqa: E501
        """
        pass

    def test_geef_haltes_in_district(self):
        """Test case for geef_haltes_in_district

        geef haltes in district  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
