"""
    De Lijn Kern Open Data Services (v1)

    Dit document beschrijft de kern operaties van de Open Data API (v1)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import unittest

import delijn_api_kern
from delijn_api_kern.api.haltes_api import HaltesApi  # noqa: E501


class TestHaltesApi(unittest.TestCase):
    """HaltesApi unit test stubs"""

    def setUp(self):
        self.api = HaltesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_geef_dienstregeling_voor_halte(self):
        """Test case for geef_dienstregeling_voor_halte

        geef de dienstregeling voor de opgegeven halte  # noqa: E501
        """
        pass

    def test_geef_dienstregeling_voor_halte_lijst(self):
        """Test case for geef_dienstregeling_voor_halte_lijst

        geef de dienstregeling voor de opgegeven halte sleutels  # noqa: E501
        """
        pass

    def test_geef_doorkomsten_voor_halte(self):
        """Test case for geef_doorkomsten_voor_halte

        geef de real-time doorkomsten voor de opgegeven halte  # noqa: E501
        """
        pass

    def test_geef_doorkomsten_voor_halte_lijst(self):
        """Test case for geef_doorkomsten_voor_halte_lijst

        geef de real-time doorkomsten voor de opgegeven halte sleutels  # noqa: E501
        """
        pass

    def test_geef_halte(self):
        """Test case for geef_halte

        geef een halte op basis van het opgegeven haltenummer  # noqa: E501
        """
        pass

    def test_geef_halte_lijnrichtingen_lijst(self):
        """Test case for geef_halte_lijnrichtingen_lijst

        geef de lijnrichtingen die de opgegeven halte bedienen op basis van een lijst van halte sleutels  # noqa: E501
        """
        pass

    def test_geef_halte_lijst(self):
        """Test case for geef_halte_lijst

        geef een lijst van haltes op basis van een lijst van halte sleutels  # noqa: E501
        """
        pass

    def test_geef_haltes(self):
        """Test case for geef_haltes

        geef alle haltes  # noqa: E501
        """
        pass

    def test_geef_haltes_indebuurt(self):
        """Test case for geef_haltes_indebuurt

        geef de haltes van de verschillende vervoersmaatschappijen in de buurt van de opgegeven coordinaten  # noqa: E501
        """
        pass

    def test_geef_lijnrichtingen_voor_halte(self):
        """Test case for geef_lijnrichtingen_voor_halte

        geef de lijnrichtingen die de opgegeven halte bedienen  # noqa: E501
        """
        pass

    def test_geef_omleidingen_voor_halte(self):
        """Test case for geef_omleidingen_voor_halte

        geef de omleidingen voor de opgegeven halte  # noqa: E501
        """
        pass

    def test_geef_omleidingen_voor_halte_lijst(self):
        """Test case for geef_omleidingen_voor_halte_lijst

        geef de omleidingen voor de opgegeven halte sleutels  # noqa: E501
        """
        pass

    def test_geef_storingen_voor_halte(self):
        """Test case for geef_storingen_voor_halte

        geef de storingen voor de opgegeven halte  # noqa: E501
        """
        pass

    def test_geef_storingen_voor_halte_lijst(self):
        """Test case for geef_storingen_voor_halte_lijst

        geef de storingen de opgegeven halte sleutels  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
