"""
    De Lijn Kern Open Data Services (v1)

    Dit document beschrijft de kern operaties van de Open Data API (v1)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import unittest

import delijn_api_kern
from delijn_api_kern.api.vervoerregios_api import VervoerregiosApi  # noqa: E501


class TestVervoerregiosApi(unittest.TestCase):
    """VervoerregiosApi unit test stubs"""

    def setUp(self):
        self.api = VervoerregiosApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_geef_lijnen_voor_vervoer_regio(self):
        """Test case for geef_lijnen_voor_vervoer_regio

        geef alle lijnen in een vervoerregio  # noqa: E501
        """
        pass

    def test_geef_vervoer_regio(self):
        """Test case for geef_vervoer_regio

        geef vervoerregio  # noqa: E501
        """
        pass

    def test_geef_vervoer_regios(self):
        """Test case for geef_vervoer_regios

        geef alle vervoerregios  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
