"""
    De Lijn Kern Open Data Services (v1)

    Dit document beschrijft de kern operaties van de Open Data API (v1)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import unittest

import delijn_api_kern
from delijn_api_kern.api.omleidingen_api import OmleidingenApi  # noqa: E501


class TestOmleidingenApi(unittest.TestCase):
    """OmleidingenApi unit test stubs"""

    def setUp(self):
        self.api = OmleidingenApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_geef_omleiding(self):
        """Test case for geef_omleiding

        geef de omleiding op basis van zijn referentie id  # noqa: E501
        """
        pass

    def test_geef_omleidingen(self):
        """Test case for geef_omleidingen

        geef alle omleidingen voor een periode van hoogstens een maand  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
