"""
    De Lijn Kern Open Data Services (v1)

    Dit document beschrijft de kern operaties van de Open Data API (v1)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import delijn_api_kern
from delijn_api_kern.model.link import Link
from delijn_api_kern.model.vervoer_regio import VervoerRegio
globals()['Link'] = Link
globals()['VervoerRegio'] = VervoerRegio
from delijn_api_kern.model.vervoer_regios import VervoerRegios


class TestVervoerRegios(unittest.TestCase):
    """VervoerRegios unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testVervoerRegios(self):
        """Test VervoerRegios"""
        # FIXME: construct object with mandatory attributes with example values
        # model = VervoerRegios()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
