"""
    De Lijn Kern Open Data Services (v1)

    Dit document beschrijft de kern operaties van de Open Data API (v1)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import unittest

import delijn_api_kern
from delijn_api_kern.api.entiteiten_api import EntiteitenApi  # noqa: E501


class TestEntiteitenApi(unittest.TestCase):
    """EntiteitenApi unit test stubs"""

    def setUp(self):
        self.api = EntiteitenApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_geef_entiteit(self):
        """Test case for geef_entiteit

        geef een entiteit op basis van het opgegeven entiteitnummer  # noqa: E501
        """
        pass

    def test_geef_entiteiten(self):
        """Test case for geef_entiteiten

        geef alle entiteiten  # noqa: E501
        """
        pass

    def test_geef_gemeenten_voor_entiteit(self):
        """Test case for geef_gemeenten_voor_entiteit

        geef alle gemeenten die beheerd worden door een entiteit  # noqa: E501
        """
        pass

    def test_geef_haltes_voor_entiteit(self):
        """Test case for geef_haltes_voor_entiteit

        geef alle haltes die beheerd worden door een entiteit  # noqa: E501
        """
        pass

    def test_geef_lijnen_voor_entiteit(self):
        """Test case for geef_lijnen_voor_entiteit

        geef alle lijnen die beheerd worden door een entiteit  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
