"""
    De Lijn Kern Open Data Services (v1)

    Dit document beschrijft de kern operaties van de Open Data API (v1)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import delijn_api_kern
from delijn_api_kern.model.lijn import Lijn
from delijn_api_kern.model.link import Link
globals()['Lijn'] = Lijn
globals()['Link'] = Link
from delijn_api_kern.model.lijnen import Lijnen


class TestLijnen(unittest.TestCase):
    """Lijnen unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLijnen(self):
        """Test Lijnen"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Lijnen()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
