"""
    De Lijn Kern Open Data Services (v1)

    Dit document beschrijft de kern operaties van de Open Data API (v1)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import delijn_api_kern
from delijn_api_kern.model.lijn_kleur_code import LijnKleurCode
from delijn_api_kern.model.link import Link
globals()['LijnKleurCode'] = LijnKleurCode
globals()['Link'] = Link
from delijn_api_kern.model.lijnkleur_codes import LijnkleurCodes


class TestLijnkleurCodes(unittest.TestCase):
    """LijnkleurCodes unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLijnkleurCodes(self):
        """Test LijnkleurCodes"""
        # FIXME: construct object with mandatory attributes with example values
        # model = LijnkleurCodes()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
