"""
    De Lijn Kern Open Data Services (v1)

    Dit document beschrijft de kern operaties van de Open Data API (v1)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import delijn_api_kern
from delijn_api_kern.model.geo_coordinaat import GeoCoordinaat
from delijn_api_kern.model.lijnrichting import Lijnrichting
from delijn_api_kern.model.omleiding import Omleiding
globals()['GeoCoordinaat'] = GeoCoordinaat
globals()['Lijnrichting'] = Lijnrichting
globals()['Omleiding'] = Omleiding
from delijn_api_kern.model.voertuig_reisweg_stap_all_of import VoertuigReiswegStapAllOf


class TestVoertuigReiswegStapAllOf(unittest.TestCase):
    """VoertuigReiswegStapAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testVoertuigReiswegStapAllOf(self):
        """Test VoertuigReiswegStapAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = VoertuigReiswegStapAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
