"""
    De Lijn Kern Open Data Services (v1)

    Dit document beschrijft de kern operaties van de Open Data API (v1)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import unittest

import delijn_api_kern
from delijn_api_kern.api.gemeenten_api import GemeentenApi  # noqa: E501


class TestGemeentenApi(unittest.TestCase):
    """GemeentenApi unit test stubs"""

    def setUp(self):
        self.api = GemeentenApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_geef_gemeente(self):
        """Test case for geef_gemeente

        geef een gemeente op basis van het opgegeven gemeentenummer  # noqa: E501
        """
        pass

    def test_geef_gemeenten(self):
        """Test case for geef_gemeenten

        geef alle gemeenten  # noqa: E501
        """
        pass

    def test_geef_haltes_voor_gemeente(self):
        """Test case for geef_haltes_voor_gemeente

        geef alle haltes binnen een gemeente  # noqa: E501
        """
        pass

    def test_geef_haltes_voor_gemeentes(self):
        """Test case for geef_haltes_voor_gemeentes

        geef alle haltes voor de lijst van gemeentenummers  # noqa: E501
        """
        pass

    def test_geef_lijnen_voor_gemeente(self):
        """Test case for geef_lijnen_voor_gemeente

        geef alle lijnen die een gemeente bedienen  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
