"""
    De Lijn Kern Open Data Services (v1)

    Dit document beschrijft de kern operaties van de Open Data API (v1)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import delijn_api_kern
from delijn_api_kern.model.de_lijn_punt import DeLijnPunt
from delijn_api_kern.model.geo_coordinaat import GeoCoordinaat
from delijn_api_kern.model.link import Link
from delijn_api_kern.model.mivb_punt import MIVBPunt
from delijn_api_kern.model.nmbs_punt import NMBSPunt
from delijn_api_kern.model.tec_punt import TECPunt
globals()['DeLijnPunt'] = DeLijnPunt
globals()['GeoCoordinaat'] = GeoCoordinaat
globals()['Link'] = Link
globals()['MIVBPunt'] = MIVBPunt
globals()['NMBSPunt'] = NMBSPunt
globals()['TECPunt'] = TECPunt
from delijn_api_kern.model.punt import Punt


class TestPunt(unittest.TestCase):
    """Punt unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPunt(self):
        """Test Punt"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Punt()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
