"""
    De Lijn Kern Open Data Services (v1)

    Dit document beschrijft de kern operaties van de Open Data API (v1)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import delijn_api_kern
from delijn_api_kern.model.halte import Halte
from delijn_api_kern.model.omleiding import Omleiding
globals()['Halte'] = Halte
globals()['Omleiding'] = Omleiding
from delijn_api_kern.model.halte_omleidingen import HalteOmleidingen


class TestHalteOmleidingen(unittest.TestCase):
    """HalteOmleidingen unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testHalteOmleidingen(self):
        """Test HalteOmleidingen"""
        # FIXME: construct object with mandatory attributes with example values
        # model = HalteOmleidingen()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
