"""
    De Lijn Kern Open Data Services (v1)

    Dit document beschrijft de kern operaties van de Open Data API (v1)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import delijn_api_kern
from delijn_api_kern.model.geo_coordinaat import GeoCoordinaat
from delijn_api_kern.model.link import Link
from delijn_api_kern.model.punt import Punt
globals()['GeoCoordinaat'] = GeoCoordinaat
globals()['Link'] = Link
globals()['Punt'] = Punt
from delijn_api_kern.model.mivb_punt import MIVBPunt


class TestMIVBPunt(unittest.TestCase):
    """MIVBPunt unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMIVBPunt(self):
        """Test MIVBPunt"""
        # FIXME: construct object with mandatory attributes with example values
        # model = MIVBPunt()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
