# flake8: noqa

"""
    De Lijn Kern Open Data Services (v1)

    Dit document beschrijft de kern operaties van de Open Data API (v1)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


__version__ = "1.0.0"

# import ApiClient
from delijn_api_kern.api_client import ApiClient

# import Configuration
from delijn_api_kern.configuration import Configuration

# import exceptions
from delijn_api_kern.exceptions import OpenApiException
from delijn_api_kern.exceptions import ApiAttributeError
from delijn_api_kern.exceptions import ApiTypeError
from delijn_api_kern.exceptions import ApiValueError
from delijn_api_kern.exceptions import ApiKeyError
from delijn_api_kern.exceptions import ApiException
