"""
    De Lijn Zoek Open Data Services (v1)

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import re  # noqa: F401
import sys  # noqa: F401

from delijn_api_zoek.api_client import ApiClient, Endpoint as _Endpoint
from delijn_api_zoek.model_utils import (  # noqa: F401
    check_allowed_values,
    check_validations,
    date,
    datetime,
    file_type,
    none_type,
    validate_and_convert_types
)
from delijn_api_zoek.model.haltes_hits import HaltesHits
from delijn_api_zoek.model.lijn_richting_hits import LijnRichtingHits
from delijn_api_zoek.model.locaties_hits import LocatiesHits


class ZoekenApi(object):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client
        self.zoek_haltes_endpoint = _Endpoint(
            settings={
                'response_type': (HaltesHits,),
                'auth': [
                    'apiKeyHeader',
                    'apiKeyQuery'
                ],
                'endpoint_path': '/zoek/haltes/{zoekArgument}',
                'operation_id': 'zoek_haltes',
                'http_method': 'GET',
                'servers': None,
            },
            params_map={
                'all': [
                    'zoek_argument',
                    'huidige_positie',
                    'start_index',
                    'max_aantal_hits',
                ],
                'required': [
                    'zoek_argument',
                ],
                'nullable': [
                ],
                'enum': [
                ],
                'validation': [
                ]
            },
            root_map={
                'validations': {
                },
                'allowed_values': {
                },
                'openapi_types': {
                    'zoek_argument':
                        (str,),
                    'huidige_positie':
                        (str,),
                    'start_index':
                        (int,),
                    'max_aantal_hits':
                        (int,),
                },
                'attribute_map': {
                    'zoek_argument': 'zoekArgument',
                    'huidige_positie': 'huidigePositie',
                    'start_index': 'startIndex',
                    'max_aantal_hits': 'maxAantalHits',
                },
                'location_map': {
                    'zoek_argument': 'path',
                    'huidige_positie': 'query',
                    'start_index': 'query',
                    'max_aantal_hits': 'query',
                },
                'collection_format_map': {
                }
            },
            headers_map={
                'accept': [
                    'application/json'
                ],
                'content_type': [],
            },
            api_client=api_client
        )
        self.zoek_lijnrichtingen_endpoint = _Endpoint(
            settings={
                'response_type': (LijnRichtingHits,),
                'auth': [
                    'apiKeyHeader',
                    'apiKeyQuery'
                ],
                'endpoint_path': '/zoek/lijnrichtingen/{zoekArgument}',
                'operation_id': 'zoek_lijnrichtingen',
                'http_method': 'GET',
                'servers': None,
            },
            params_map={
                'all': [
                    'zoek_argument',
                    'huidige_positie',
                    'start_index',
                    'max_aantal_hits',
                ],
                'required': [
                    'zoek_argument',
                ],
                'nullable': [
                ],
                'enum': [
                ],
                'validation': [
                ]
            },
            root_map={
                'validations': {
                },
                'allowed_values': {
                },
                'openapi_types': {
                    'zoek_argument':
                        (str,),
                    'huidige_positie':
                        (str,),
                    'start_index':
                        (int,),
                    'max_aantal_hits':
                        (int,),
                },
                'attribute_map': {
                    'zoek_argument': 'zoekArgument',
                    'huidige_positie': 'huidigePositie',
                    'start_index': 'startIndex',
                    'max_aantal_hits': 'maxAantalHits',
                },
                'location_map': {
                    'zoek_argument': 'path',
                    'huidige_positie': 'query',
                    'start_index': 'query',
                    'max_aantal_hits': 'query',
                },
                'collection_format_map': {
                }
            },
            headers_map={
                'accept': [
                    'application/json'
                ],
                'content_type': [],
            },
            api_client=api_client
        )
        self.zoek_locaties_endpoint = _Endpoint(
            settings={
                'response_type': (LocatiesHits,),
                'auth': [
                    'apiKeyHeader',
                    'apiKeyQuery'
                ],
                'endpoint_path': '/zoek/locaties/{zoekArgument}',
                'operation_id': 'zoek_locaties',
                'http_method': 'GET',
                'servers': None,
            },
            params_map={
                'all': [
                    'zoek_argument',
                    'huidige_positie',
                    'start_index',
                    'max_aantal_hits',
                ],
                'required': [
                    'zoek_argument',
                ],
                'nullable': [
                ],
                'enum': [
                ],
                'validation': [
                ]
            },
            root_map={
                'validations': {
                },
                'allowed_values': {
                },
                'openapi_types': {
                    'zoek_argument':
                        (str,),
                    'huidige_positie':
                        (str,),
                    'start_index':
                        (int,),
                    'max_aantal_hits':
                        (int,),
                },
                'attribute_map': {
                    'zoek_argument': 'zoekArgument',
                    'huidige_positie': 'huidigePositie',
                    'start_index': 'startIndex',
                    'max_aantal_hits': 'maxAantalHits',
                },
                'location_map': {
                    'zoek_argument': 'path',
                    'huidige_positie': 'query',
                    'start_index': 'query',
                    'max_aantal_hits': 'query',
                },
                'collection_format_map': {
                }
            },
            headers_map={
                'accept': [
                    'application/json;charset=UTF-8'
                ],
                'content_type': [],
            },
            api_client=api_client
        )

    def zoek_haltes(
        self,
        zoek_argument,
        **kwargs
    ):
        """zoekHaltes  # noqa: E501

        zoekHaltes  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.zoek_halte(zoek_argument, async_req=True)
        >>> result = thread.get()

        Args:
            zoek_argument (str): het zoekargument

        Keyword Args:
            huidige_positie (str): de latitude en longitude coordinaat waarden gescheiden door komma bv, 51.056064,3.797336 van de lokatie waarvoor haltes in de buurt gezocht wordt. [optional]
            start_index (int): Format - int32. de start positie in de lijst van gevonden haltes. [optional] if omitted the server will use the default value of 0
            max_aantal_hits (int): Format - int32. het maximaal aantal haltes aangeleverd door deze service . [optional] if omitted the server will use the default value of 10
            _return_http_data_only (bool): response data without head status
                code and headers. Default is True.
            _preload_content (bool): if False, the urllib3.HTTPResponse object
                will be returned without reading/decoding response data.
                Default is True.
            _request_timeout (int/float/tuple): timeout setting for this request. If
                one number provided, it will be total request timeout. It can also
                be a pair (tuple) of (connection, read) timeouts.
                Default is None.
            _check_input_type (bool): specifies if type checking
                should be done one the data sent to the server.
                Default is True.
            _check_return_type (bool): specifies if type checking
                should be done one the data received from the server.
                Default is True.
            _spec_property_naming (bool): True if the variable names in the input data
                are serialized names, as specified in the OpenAPI document.
                False if the variable names in the input data
                are pythonic names, e.g. snake case (default)
            _content_type (str/None): force body content-type.
                Default is None and content-type will be predicted by allowed
                content-types and body.
            _host_index (int/None): specifies the index of the server
                that we want to use.
                Default is read from the configuration.
            _request_auths (list): set to override the auth_settings for an a single
                request; this effectively ignores the authentication
                in the spec for a single request.
                Default is None
            async_req (bool): execute request asynchronously

        Returns:
            HaltesHits
                If the method is called asynchronously, returns the request
                thread.
        """
        kwargs['async_req'] = kwargs.get(
            'async_req', False
        )
        kwargs['_return_http_data_only'] = kwargs.get(
            '_return_http_data_only', True
        )
        kwargs['_preload_content'] = kwargs.get(
            '_preload_content', True
        )
        kwargs['_request_timeout'] = kwargs.get(
            '_request_timeout', None
        )
        kwargs['_check_input_type'] = kwargs.get(
            '_check_input_type', True
        )
        kwargs['_check_return_type'] = kwargs.get(
            '_check_return_type', True
        )
        kwargs['_spec_property_naming'] = kwargs.get(
            '_spec_property_naming', False
        )
        kwargs['_content_type'] = kwargs.get(
            '_content_type')
        kwargs['_host_index'] = kwargs.get('_host_index')
        kwargs['_request_auths'] = kwargs.get('_request_auths', None)
        kwargs['zoek_argument'] = \
            zoek_argument
        return self.zoek_haltes_endpoint.call_with_http_info(**kwargs)

    def zoek_lijnrichtingen(
        self,
        zoek_argument,
        **kwargs
    ):
        """zoekLijnrichtingen  # noqa: E501

        zoekLijnrichtingen  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.zoek_lijnrichtingen(zoek_argument, async_req=True)
        >>> result = thread.get()

        Args:
            zoek_argument (str): het zoekargument

        Keyword Args:
            huidige_positie (str): de latitude en longitude coordinaat waarden gescheiden door komma bv, 51.056064,3.797336 van de lokatie waarvoor lijnen in de buurt gezocht wordt. [optional]
            start_index (int): Format - int32. de start positie in de lijst van gevonden lijnen. [optional] if omitted the server will use the default value of 0
            max_aantal_hits (int): Format - int32. het maximaal aantal lijnen aangeleverd door deze service . [optional] if omitted the server will use the default value of 10
            _return_http_data_only (bool): response data without head status
                code and headers. Default is True.
            _preload_content (bool): if False, the urllib3.HTTPResponse object
                will be returned without reading/decoding response data.
                Default is True.
            _request_timeout (int/float/tuple): timeout setting for this request. If
                one number provided, it will be total request timeout. It can also
                be a pair (tuple) of (connection, read) timeouts.
                Default is None.
            _check_input_type (bool): specifies if type checking
                should be done one the data sent to the server.
                Default is True.
            _check_return_type (bool): specifies if type checking
                should be done one the data received from the server.
                Default is True.
            _spec_property_naming (bool): True if the variable names in the input data
                are serialized names, as specified in the OpenAPI document.
                False if the variable names in the input data
                are pythonic names, e.g. snake case (default)
            _content_type (str/None): force body content-type.
                Default is None and content-type will be predicted by allowed
                content-types and body.
            _host_index (int/None): specifies the index of the server
                that we want to use.
                Default is read from the configuration.
            _request_auths (list): set to override the auth_settings for an a single
                request; this effectively ignores the authentication
                in the spec for a single request.
                Default is None
            async_req (bool): execute request asynchronously

        Returns:
            LijnRichtingHits
                If the method is called asynchronously, returns the request
                thread.
        """
        kwargs['async_req'] = kwargs.get(
            'async_req', False
        )
        kwargs['_return_http_data_only'] = kwargs.get(
            '_return_http_data_only', True
        )
        kwargs['_preload_content'] = kwargs.get(
            '_preload_content', True
        )
        kwargs['_request_timeout'] = kwargs.get(
            '_request_timeout', None
        )
        kwargs['_check_input_type'] = kwargs.get(
            '_check_input_type', True
        )
        kwargs['_check_return_type'] = kwargs.get(
            '_check_return_type', True
        )
        kwargs['_spec_property_naming'] = kwargs.get(
            '_spec_property_naming', False
        )
        kwargs['_content_type'] = kwargs.get(
            '_content_type')
        kwargs['_host_index'] = kwargs.get('_host_index')
        kwargs['_request_auths'] = kwargs.get('_request_auths', None)
        kwargs['zoek_argument'] = \
            zoek_argument
        return self.zoek_lijnrichtingen_endpoint.call_with_http_info(**kwargs)

    def zoek_locaties(
        self,
        zoek_argument,
        **kwargs
    ):
        """zoekLocaties  # noqa: E501

        zoekLocaties  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.zoek_locaties(zoek_argument, async_req=True)
        >>> result = thread.get()

        Args:
            zoek_argument (str): het zoekargument

        Keyword Args:
            huidige_positie (str): momenteel niet ondersteund voor lokaties. [optional]
            start_index (int): Format - int32. de start positie in de lijst van gevonden lokaties. [optional] if omitted the server will use the default value of 0
            max_aantal_hits (int): Format - int32. het maximaal aantal lokaties aangeleverd door deze service . [optional] if omitted the server will use the default value of 10
            _return_http_data_only (bool): response data without head status
                code and headers. Default is True.
            _preload_content (bool): if False, the urllib3.HTTPResponse object
                will be returned without reading/decoding response data.
                Default is True.
            _request_timeout (int/float/tuple): timeout setting for this request. If
                one number provided, it will be total request timeout. It can also
                be a pair (tuple) of (connection, read) timeouts.
                Default is None.
            _check_input_type (bool): specifies if type checking
                should be done one the data sent to the server.
                Default is True.
            _check_return_type (bool): specifies if type checking
                should be done one the data received from the server.
                Default is True.
            _spec_property_naming (bool): True if the variable names in the input data
                are serialized names, as specified in the OpenAPI document.
                False if the variable names in the input data
                are pythonic names, e.g. snake case (default)
            _content_type (str/None): force body content-type.
                Default is None and content-type will be predicted by allowed
                content-types and body.
            _host_index (int/None): specifies the index of the server
                that we want to use.
                Default is read from the configuration.
            _request_auths (list): set to override the auth_settings for an a single
                request; this effectively ignores the authentication
                in the spec for a single request.
                Default is None
            async_req (bool): execute request asynchronously

        Returns:
            LocatiesHits
                If the method is called asynchronously, returns the request
                thread.
        """
        kwargs['async_req'] = kwargs.get(
            'async_req', False
        )
        kwargs['_return_http_data_only'] = kwargs.get(
            '_return_http_data_only', True
        )
        kwargs['_preload_content'] = kwargs.get(
            '_preload_content', True
        )
        kwargs['_request_timeout'] = kwargs.get(
            '_request_timeout', None
        )
        kwargs['_check_input_type'] = kwargs.get(
            '_check_input_type', True
        )
        kwargs['_check_return_type'] = kwargs.get(
            '_check_return_type', True
        )
        kwargs['_spec_property_naming'] = kwargs.get(
            '_spec_property_naming', False
        )
        kwargs['_content_type'] = kwargs.get(
            '_content_type')
        kwargs['_host_index'] = kwargs.get('_host_index')
        kwargs['_request_auths'] = kwargs.get('_request_auths', None)
        kwargs['zoek_argument'] = \
            zoek_argument
        return self.zoek_locaties_endpoint.call_with_http_info(**kwargs)

