"""
    De Lijn Zoek Open Data Services (v1)

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import delijn_api_zoek
from delijn_api_zoek.model.lijnrichting import Lijnrichting
globals()['Lijnrichting'] = Lijnrichting
from delijn_api_zoek.model.lijn_richting_hits import LijnRichtingHits


class TestLijnRichtingHits(unittest.TestCase):
    """LijnRichtingHits unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLijnRichtingHits(self):
        """Test LijnRichtingHits"""
        # FIXME: construct object with mandatory attributes with example values
        # model = LijnRichtingHits()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
