"""
    De Lijn Zoek Open Data Services (v1)

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import unittest

import delijn_api_zoek
from delijn_api_zoek.api.zoeken_api import ZoekenApi  # noqa: E501


class TestZoekenApi(unittest.TestCase):
    """ZoekenApi unit test stubs"""

    def setUp(self):
        self.api = ZoekenApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_zoek_haltes(self):
        """Test case for zoek_haltes

        zoekHaltes  # noqa: E501
        """
        pass

    def test_zoek_lijnrichtingen(self):
        """Test case for zoek_lijnrichtingen

        zoekLijnrichtingen  # noqa: E501
        """
        pass

    def test_zoek_locaties(self):
        """Test case for zoek_locaties

        zoekLocaties  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
