"""
    De Lijn Zoek Open Data Services (v1)

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import delijn_api_zoek
from delijn_api_zoek.model.geo_coordinaat import GeoCoordinaat


class TestGeoCoordinaat(unittest.TestCase):
    """GeoCoordinaat unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGeoCoordinaat(self):
        """Test GeoCoordinaat"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GeoCoordinaat()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
